name: Flutter CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
      - name: Get dependencies
        run: flutter pub get
      - name: Check code format
        run: flutter format --set-exit-if-changed .
      - name: Run linter
        run: flutter analyze .
      - name: Run tests
        run: flutter test
      - name: Generate android APK
        run: flutter build apk --profile
